# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 05:44
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(help_text='위도,경도 포맷으로 입력', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
