# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=20),
        ),
    ]
