# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:32
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160803_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='dong',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='gu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='road',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number1',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
