# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 02:40
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160803_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number1',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
    ]
