# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 07:19
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160803_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number1',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='test_field',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
