# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 03:33
from __future__ import unicode_literals

import blog.fields
import blog.models
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160807_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='jjal',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number1',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=blog.models.myupload_to),
        ),
    ]
