# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pokemon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jiwoo', max_length=20)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lnglat', models.CharField(help_text='위도,경도 포맷으로 입력', max_length=50, validators=[pokemon.models.lnglat_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('captured_at', models.DateTimeField()),
                ('captured_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Person')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.Place')),
            ],
        ),
    ]
