# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='captured_at',
        ),
    ]
